### ISSUE TITLE
Add -v options to see output of common commands

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#10]
Like `datacats install`, `datacats create`, and `datacats deploy`

**Comment by dborzov** [comment]
What is it supposed to show specifically?

I think, at the moment it channels the `stderr` of remote command being executed to datacat command's `stdout`. Is that a temporary thing or the longer term design decision? Should it channel the `stderr` only with the `verbose` key on? 

@wardi , @JackMc any thoughts?

**Comment by JackMc** [comment]
A lot of the things that are run within those commands are ran with their stdout going to the docker logs (accessible through "datacats logs"). I think what is being asked here is that there be a way (a -v --verbose option) to see this output directly on the console.

**Comment by wardi** [comment]
datacats deploy is now verbose (it shows the rsync output) it could be used as an example of a verbose command. I think install should be verbose by default too, but not during create - that one *should* always work without downloading anything.

So I'd say, let's not bother with a --verbose let's just make install verbose by default too

**Comment by JackMc** [comment]
So the install step of create shouldn't be verbose, but an explicit command-line use of install should be verbose?

**Comment by wardi** [comment]
Yeah, that makes sense to me

**Comment by JackMc** [comment]
:+1:

**Comment by wardi** [comment]
we have better deploy errors #157 and verbose installs by default now #158
