### ISSUE TITLE
Configuration options plan

### ISSUE THREAD

**Issue by wardi** [datacats/datacats#107]
1. **global**: ~/.datacats/config
2. **user**: ~/.datacats/user-profile/config
3. **env**: *path-to-environment-dir*/.datacats-environment
4. **datadir**: ~/.datacats/<name>/

where a setting may appear in multiple locations the higher-numbered setting overrides

| option | global | user | env | datadir |
| --- | --- | --- | --- | --- |
| DB passwords | | | | :white_check_mark: |
| site_url | | | | :white_check_mark: |
| port | | | :white_check_mark: | :white_check_mark: |
| address | :white_check_mark: | | | :white_check_mark: |
| deploy_target | | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| ckan_version | | | :white_check_mark: | |
| future service containers | | | :white_check_mark: | |
| ssh_public_key | | :white_check_mark: | |
| ssh_private_key | | :white_check_mark: | |
| DNS | :white_check_mark: | | | |
| always_prod | :white_check_mark: | | | |

This is how I think our settings should be arranged. These are not yet in the right places:
- [ ] site_url
- [ ] port
- [ ] address
- [ ] deploy_target
- [ ] DNS
- [ ] always_prod

**Comment by JackMc** [comment]
As some of these are going to be breaking changes (i.e. moving always prod to only global will break some people's confs) should we still look in the old location?

**Comment by JackMc** [comment]
Should a global configuration option be set when it's changed on the command line, or just overridden for that one run?

**Comment by wardi** [comment]
good question. Probably just that one run, but that's inconsistent with what we're doing for the environment settings like port and address.

how about we document our slightly uncommon saving-behaviour of the port and address options and do the same for dns, just tell the user it will be saved and applied to all new and existing environments.

It's either that or tell users where to find the file to edit to make the change permanent. That option seems harder for us and them.

**Comment by JackMc** [comment]
Would it be better just to open a file to each of these configuration files at constructor-time and then deal with them as needed in their relevant methods? Currently, we read and delete them as needed which might get messy if as suggested we have 4 config files to read from

**Comment by wardi** [comment]
This is already out of date (since multisite) and I'd like to revisit some of these since we're also not storing the --production and --no-reload options (and clobbering them on datacats install) We should be more consistent and predictable about how we handle options

**Comment by JackMc** [comment]
Update for sites
