### ISSUE TITLE
datacats misreports address it is running on

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#108]
This is a minor regression error. datacats thinks it is running on localhost, but it is running for me on the docker VM host ip. It used to report properly, but now it doesn't.

This happens on latest master, 618c4c3
```
datacats info -q
http://127.0.0.1:5195/
```

**Comment by JackMc** [comment]
https://github.com/datacats/datacats/pull/88/files#diff-f6fb7f89c46db2aad5cc2111e4873a03R675 is the cause here. Fixing.

**Comment by JackMc** [comment]
@deniszgonjanin Please verify that #109 fixes it :)

**Comment by deniszgonjanin** [comment]
:+1:
