### ISSUE TITLE
Run tests automatically prior to commit

### ISSUE THREAD

**Issue by JackMc** [datacats/datacats#117]
This will make our process much easier so we don't get big glaring **EVERYTHING IS BROKEN PANIC** messages when someone forgot a tab.

**Comment by JackMc** [comment]
Turns out this isn't possible, per se. An alternative seems to be having a pre-commit hook in our directories for people to optionally install into their .git/hooks directory.

**Comment by deniszgonjanin** [comment]
Yea, let's not force people to run tests before committing. It slows down your workflow. I think it's enough to have a CI that automatically builds from github

**Comment by JackMc** [comment]
Our tests take (currently) 0.236s. I'm referring to the four unittest tests we currently have:
* 2 name validation checks (probably could disable)
* 2 style checks (pep8 and pyflakes)
