### ISSUE TITLE
Support watching less files

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#118]
`datacats less` should support a `--watch` parameter, and recompile less every time a less file is saved

**Comment by deniszgonjanin** [comment]
I tried an approach with something like [watchdog](https://github.com/gorakhargosh/watchdog). The idea is that it would run inside the container and pick up filesystem events, then recompile `less` on changes.

However, there is a problem with lxc containers where `inotify` events are handled by the host OS only - whatever is running on the container does not receive them.

There are a couple of possible solutions:

1. datacats itself could watch for filesystem events on the host OS, running a one-off container to recompile `less` every time a change happens. This sucks because of container startup time and possible difficulty in getting this to run well on Windows.

2. We could poll for filesystem changes instead of listening to inotify events. This sucks because it is not as responsive and the user needs to wait an extra couple seconds for the changes to get picked up and `less` to recompile, which makes the workflow more sucky. There is also a small performance cost.

**Comment by deniszgonjanin** [comment]
Comparing the two would be good. We should do whichever one is the fastest for the designer to see their changes. 

A third option is to listen to file events locally, but have a long-running less container nonetheless, which can be signaled to recompile less - avoiding the container startup time.

**Comment by JackMc** [comment]
I was thinking the same approach as you were talking about initially (with inotify in the container). Sucks that that won't work.

We need a daemon-like process to recompile these files then I guess.

**Comment by JackMc** [comment]
After some research apparently the typical inotify approach works, but not on boot2docker because of the VM extra layer of abstraction.

**Comment by deniszgonjanin** [comment]
Right, let's try the approach of watching locally and running one-off
recompile containers first. I have a better feeling about that approach

**Comment by wardi** [comment]
:+1:

**Comment by wardi** [comment]
We also need to investigate if we're compiling all the files, I remember seeing a what looked like a bunch of css themes or something, but never investigated how to enable them

**Comment by JackMc** [comment]
Yeah, I'm gonna look at the CKAN script and try to emulate it.

**Comment by JackMc** [comment]
I looked pretty hard into ways to do file watching reliably over vboxsf. It seems it's just unsupported entirely at a kernel level for nfs and vboxsf.

**Comment by JackMc** [comment]
It seems like a really hard thing to do right to have a daemon which watches for less file changes cross-platform (especially for Windows...ew. We might have to run a service or whatever the bastardized thing of the week is to run background processes).

**Comment by deniszgonjanin** [comment]
I'd be very happy with a well-working Linux/OSX version. Most people designing CKAN using less are going to be on a Mac

**Comment by JackMc** [comment]
So for cross-platform file watching in Python we have the following options from what I've found:
https://github.com/gorakhargosh/watchdog
https://github.com/facebook/watchman
These seem to be the only options which don't just do dumb polling.

As for running a daemon reliably on Linux/Mac OS X and managing its state, I will have to do more research.
