### ISSUE TITLE
domain name collision for datacats deploy --create

### ISSUE THREAD

**Issue by dborzov** [datacats/datacats#129]
When you attempt to deploy a new datacat environment onto the server and there is already one with that name, we should get an error message stating that.

**Comment by JackMc** [comment]
What happens right now?

**Comment by dborzov** [comment]
Oh, never mind, it actually should be fixed on the server side.

The remote server command for `create` sends the internal API request which fails without explanation in case of collision. The client only shows that remote command `create` failed.
