### ISSUE TITLE
When web logs get sufficiently large, datacats logs hangs

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#138]
By default docker logs to the file system I believe. In addition to `datacats logs` hanging, the default behavior may cause disk space issues on production environments.

Docker 1.6 does support logging to syslog instead with docker run --log-driver=syslog

**Comment by JackMc** [comment]
The Docker docs indicate that logging to syslog may break how we currently implement 'datacats logs':

![Docker logs](http://i.imgur.com/lNtYK30.png)

**Comment by JackMc** [comment]
So we would have to keep some record of where the user is logging to and tell them that they'll have to use syslog instead of our command.

**Comment by deniszgonjanin** [comment]
Perhaps investigate how we can rotate the logs instead?

**Comment by deniszgonjanin** [comment]
P.S. this isn't a big priority, more something to keep on the radar

**Comment by JackMc** [comment]
Okie :smile:

**Comment by JackMc** [comment]
Can you check if #141 addresses this issue well enough?
