### ISSUE TITLE
datacats create should work without internet connection

### ISSUE THREAD

**Issue by wardi** [datacats/datacats#147]
Everything required is in the preloaded virtualenv, we shouldn't fail from datacats create if we can't reach pypi.

**Comment by wardi** [comment]
@JackMc  This is in the wrong place: https://github.com/datacats/datacats/blob/master/datacats/scripts/install_package.sh#L11  pip install -e doesn't download anything

Please move it to install_requirements.sh instead

**Comment by JackMc** [comment]
Okay.
