### ISSUE TITLE
Add support for less-watching container

### ISSUE THREAD

**Issue by wardi** [datacats/datacats#15]
currently we only regenerate main.debug.css in the preload image. Add support for running the less-watching and automatic css rebuilding from a node container.

**Comment by wardi** [comment]
@JackMc would you put this on your list? We're going to need it soon for rebuilding the css from less files. The current code that does this is under the docker directory

**Comment by JackMc** [comment]
Sounds good! :)

**Comment by JackMc** [comment]
https://github.com/jgreene/watch-less This tool does what we want to do. Should I use it or should I write my own script?
