### ISSUE TITLE
Not enough things are called datacats in this project

### ISSUE THREAD

**Issue by dborzov** [datacats/datacats#151]
We need to find something else we can rename to datacats. Renaming the company, and most of the directories is good, but we need to go deeper. 

![Img](http://websanya.ru/wp-content/uploads/2014/07/we-need-to-go-deeper.jpg)

**Comment by deniszgonjanin** [comment]
What if we sponsored @JackMc's education if he changed his name to Datacat McCraken?

**Comment by JackMc** [comment]
I would be okay with that :D

**Comment by wardi** [comment]
![badgers](https://cloud.githubusercontent.com/assets/153258/7971286/9d7902bc-0a11-11e5-911c-85b27832af68.jpg)

**Comment by JackMc** [comment]
Are Datacats scared of snakes?

**Comment by JackMc** [comment]
;(
