### ISSUE TITLE
Idea: datacats reset command

### ISSUE THREAD

**Issue by wardi** [datacats/datacats#170]
Delete the files, reset the db and recreate the admin user.  sort of like purge + init but just for one site

**Comment by JackMc** [comment]
So basically equivalent to:
```
datacats purge -s mysite myenv
datacats init -s mysite myenv
```

??

**Comment by wardi** [comment]
yes, except without the install step and if it's the last site it won't destroy the venv and reinstall everything

**Comment by JackMc** [comment]
Ahh ok makes sense :)

**Comment by wardi** [comment]
I don;t know if this makes more sense as a separate command or an option on `init`

**Comment by dborzov** [comment]
Let's drop the current `init` completely, and have `reset` with options to replicate what `init` does now.

`init` as a CLI command is now an idiom that stands for completely different things. Let's count all the examples:
- `git init`
-`heroku init`
- `boot2docker init`
- `ipfs init`

and the list goes and goes.

`init` is expected to either:
1) setup the computer for work with the tool (e.g. pull the needed docker images and set up ~/.datacats/user_profile in our case)
2) or do what `datacats create` does, that is create an instance or an environment

**Comment by JackMc** [comment]
That might be a good idea.

**Comment by wardi** [comment]
`reset` doesn't make sense as the way to add new sites to an environment

**Comment by wardi** [comment]
`datacats assemble!`

![thundercats assemble](http://i54.tinypic.com/2mfcawk.gif)

**Comment by dborzov** [comment]
:joy::joy::joy: `datacats assemble!` is the only command we will ever need

**Comment by JackMc** [comment]
Does the CKAN ``paster --plugin=ckan db init`` command reset the database (i.e. get rid of everything)?

**Comment by deniszgonjanin** [comment]
No, `paster --plugin=ckan db clean` does that

**Comment by JackMc** [comment]
Thank you! :)

**Comment by wardi** [comment]
Might need a `paster --plugin=ckan search-index clear` too (I think these commands should be merged)

**Comment by wardi** [comment]
If we're implementing a reset I wouldn't trust any of these things. I'd just nuke the directories and create them again.
