### ISSUE TITLE
Migration warning should be explained better

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#171]
This message should be expanded on. It tells me that important changes are happening, but doesn't tell me why I should care, or in which cases I may be unwise to perform the migration. It gives the user a choice to make, without explaining any implications of that choice.

```
This migration will change the format of your datadir. Are you sure? (y/n) [n]:
```

**Comment by JackMc** [comment]
The only problem with being more specific is that we allow for migrations from 1->2 and 2->1 and eventually n_1->n_2

**Comment by JackMc** [comment]
So anything more specific may be incorrect in the 2->1 direction

**Comment by deniszgonjanin** [comment]
Maybe just explaining why migrating would ever be dangerous or potentially destructive. As a user, is there a scenario where I should think twice before migrating?

**Comment by JackMc** [comment]
#176 fixes this
