### ISSUE TITLE
Give helpful suggestion on DNS failure

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#172]
The DNS issue often happens to me when I move physically to a different wifi network. The boot2docker VMs network settings get screwed up, necessitating a reboot. The following message should give the helpful suggestion to restart boot2docker. Eg:

```
----------------------------------------
datacats: problem was encountered:
     Couldn't connect to PyPi. Is your DNS configured correctly?

If you are using boot2docker, try restarting the VM:
boot2docker down
boot2docker up
----------------------------------------
```

**Comment by JackMc** [comment]
:+1:

**Comment by dborzov** [comment]
I am confused. When does this happen and how to reproduce it? At what stage datacats runs `pip` within the container?

**Comment by JackMc** [comment]
Datacats run ``pip`` at install-time. It happens when you switch networks while using boot2docker.

**Comment by JackMc** [comment]
boot2docker sometimes isn't smart enough to keep up with the DNS.

**Comment by JackMc** [comment]
#172 fixes this.
