### ISSUE TITLE
problem with datacats reload/start -p

### ISSUE THREAD

**Issue by wardi** [datacats/datacats#173]
no helpful logs, and it's broken back to at least 0.9.3
```
----------------------------------------
datacats: problem was encountered:
     Error while starting web container:
     
----------------------------------------
```

**Comment by JackMc** [comment]
Not broken on Mac
=

**Comment by JackMc** [comment]
Will tryon my VM tomorrow

**Comment by JackMc** [comment]
Cannot reproduce on Linux. Here is the script I'm using. Is there anything wrong with this as a test case?

HEAD = 8283a8ef2424d09f3d81f544291b46a0531d8cb8

```bash
#!/bin/bash

rm -rf ~/virtualenvs/testenv
# Remove all containers matching "testenv"
docker stop $(docker ps -a | egrep "testenv" | tr -s ' ' | cut -f1 -d ' ')
docker rm $(docker ps -a | egrep "testenv" | tr -s ' ' | cut -f1 -d ' ')
sudo rm -rf ~/.datacats/testenv
sudo rm -rf ./testenv
virtualenv datacats.bisect
source datacats.bisect/bin/activate
python setup.py develop

datacats create testenv -bn
datacats reload -p testenv
deactivate
```

**Comment by wardi** [comment]
That's promising, maybe it's just my machine/venv then. I like that better than -p being broken for ages.

**Comment by JackMc** [comment]
Just fixed up the script, if you could try it to see if it is reproducible on your machine with that script that'd be cool

**Comment by JackMc** [comment]
Is this fixed?

**Comment by wardi** [comment]
I can no longer reproduce this
