### ISSUE TITLE
add postgis tables/functions to dbs without them

### ISSUE THREAD

**Issue by wardi** [datacats/datacats#184]
Let's see if we can silently detect and add missing postgis tables/functions to dbs as we are starting them so that existing sites can start using the spatial extension.

It might be time to stop relying on the postgres ENTRYPOINT magic script and instead explicitly run a container with a script that checks and creates/upgrades existing dbs, then start the container that actually serves postgres as a separate command. That will eliminate an existing race condition that was just worked around by reordering steps that create calls.

**Comment by JackMc** [comment]
:+1:

**Comment by wardi** [comment]
tweak has this option now
