### ISSUE TITLE
Import error during datacats pull on Ubuntu

### ISSUE THREAD

**Issue by florianm** [datacats/datacats#185]
Ubuntu 14.04, python 2.7.6, requests 2.7.0 is unable to import `requests.packages` and below. 

E.g. `datacats pull` throws this ImportError:
```
from requests.packages.urllib3.exceptions import InsecureRequestWarning, InsecurePlatformWarning
ImportError: No module named packages.urllib3.exceptions
```

A workaround along [these lines](https://github.com/locustio/locust/issues/148) didn't work either as I couldn't find a way to [import the two required warnings](https://github.com/florianm/datacats/blob/185-import-error/datacats/docker.py#L10).

Strangely, requests (v2.7.0) implements these errors (although with a [pass](https://github.com/kennethreitz/requests/blob/master/requests/packages/urllib3/exceptions.py#L152)).

This is probably a problem between requests and my fairly fresh Ubuntu VM, but it still prevents me from using datacats. Any pointers would be highly welcome!

**Comment by JackMc** [comment]
Thank you for the report! I'll look into it now :)

**Comment by JackMc** [comment]
Are you running datacats off master or off of the latest stable release?

**Comment by JackMc** [comment]
Looks like master. Also are you running in a venv?

**Comment by florianm** [comment]
Thanks for the quick reply!
Above error was on bespoke Ubuntu 14.04 VM (AWS t2.medium) after `pip install datacats` as per quickstart.

I've since pip uninstalled datacats, created a virtualenv, within that I've pip installed requests and datacats. Pip freeze:
```
PyYAML==3.11
argh==0.26.1
argparse==1.2.1
args==0.1.0
backports.ssl-match-hostname==3.4.0.2
clint==0.4.1
datacats==0.11.0
docker-py==1.2.2
docopt==0.6.2
pathtools==0.1.2
pbr==1.1.1
requests==2.7.0
six==1.9.0
stevedore==1.5.0
virtualenv==13.0.3
virtualenv-clone==0.2.5
virtualenvwrapper==4.6.0
watchdog==0.8.3
websocket-client==0.32.0
wsgiref==0.1.2
```
Again, requests 2.7.0. Now I'm able to import `requests.packages.urllib3.exceptions` fine. I can't figure out why previously I couldn't. I also ran into [this bug](https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1306991) (with datacats and with another project with a virtualenv). I can `datacats pull` now and am running into a different error, but the request import error seems fixed. 
So the error is on my end, I'll close this issue!
