### ISSUE TITLE
requests.connections.ConnectionError during datacats pull if docker is installed from apt-get

### ISSUE THREAD

**Issue by florianm** [datacats/datacats#186]
A really silly stumbling block in the installation process for people like me who can't read - installing Docker via apt-get (because who follows links to read that the default installation method won't work) will cause the following problems, which ultimately come from missing kernel modules / permissions / docker installation steps:

This issue exists both on Ubuntu 14.10 and Ubuntu 14.04. Using virtualenvwrapper.
```
# pip has a bug and requires requests 2.2.1
sudo easy_install requests==2.2.1
mkproject datacats # creates and activates virtualenv "datacats"
# inside virtualenv "datacats":
pip install virtualenvwrapper datacats
datacats pull
Pulling image datacats/webTraceback (most recent call last):
...
  File "/home/florianm/virtualenvs/datacats/local/lib/python2.7/site-packages/docker/client.py", line 106, in _get
 ...
requests.exceptions.ConnectionError: ('Connection aborted.', error(13, 'Permission denied'))
```

This error appears to happen in [datacats/docker/client.py:87](https://github.com/datacats/datacats/blob/master/datacats/docker.py#L94) in an ipython shell in both my 
Ubuntu versions:
```
from docker import Client
version_client = Client(version='1.16') # substituted version, omitted **kwargs
version_client.version()
# throws:
ConnectionError: ('Connection aborted.', error(13, 'Permission denied'))
```

These issues do not exist after Docker was installed correctly, in this case (Ubuntu 14.*):
```
sudo su
wget -qO- https://get.docker.com/ | sh
```

Posting this as issue as it tricked me long enough to wish for a short mention in the quickstart section for Ubuntu users to not apt-get install docker. Or at least in the troubleshooting section, so the quickstart stays as elegantly concise as it is.

**Comment by dborzov** [comment]
Thanks for reporting this issue! 
We need to update installation instructions and mention that docker's version at apt-get is obsolete for our needs.

**Comment by dborzov** [comment]
@wardi , @JackMc what is this "workaround" about?

[Here](https://github.com/datacats/datacats/commit/85a70a271e51fd27a8a563b60004cc30ab663ba0#diff-4b174a8e770d20c80e7ab2695942b02bR76):
```python
        version_client = Client(version=MINIMUM_API_VERSION, **_docker_kwargs)
        try:
            api_version = version_client.version()['ApiVersion']
        except ConnectionError:
            # workaround for connection issue when old version specified
            # on some clients
            version_client = Client(**_docker_kwargs)
            api_version = version_client.version()['ApiVersion']
```
what was the logic for attempting to connect to Docker without MINIMUM_API_VERSION if connection fails? 

Should it just be:
```python
        version_client = Client(version=MINIMUM_API_VERSION, **_docker_kwargs)
        try:
            api_version = version_client.version()['ApiVersion']
        except ConnectionError:
            raise DatacatsError("cannot connect to docker, install right version or somethin")

```

**Comment by wardi** [comment]
@dborzov some combinations of docker and docker-py versions caused a failure when the version was requested when specifying a minimum version (IIRC that minimum wasn't supported) but *worked* when connecting without specifying a version. Others needed the version.. There's a comment at the top of the file about how difficult it has been to keep all this working.

**Comment by wardi** [comment]
Let's go full belt-and-suspenders on this one. We can catch this exception and tell the user to get a newer version of docker instead of just improving our docs

**Comment by JackMc** [comment]
Okie dokie

**Comment by florianm** [comment]
Even after installing docker the right way (tm)
```
sudo su
wget -qO- https://get.docker.com/ | sh
```
remember that you'll have to add the current user to the docker group with
`sudo usermod -aG docker USERNAME`, then logout and login again to apply that change.

Simple test: if `docker ps` fails with permission error (/var/run/docker socket IIRC), but `sudo docker ps` works, above step might be missing.
