### ISSUE TITLE
reset silently exits when no environment specified

### ISSUE THREAD

**Issue by wardi** [datacats/datacats#191]
it should default to `.` for the environment like the other commands.

**Comment by JackMc** [comment]
Fixed in 2b0a451b7bf9741a494967f48d6eee080adffdd6

**Comment by wardi** [comment]
ok, but why was it silently exiting instead of giving an error that the environment should have been given?

**Comment by JackMc** [comment]
Investigating this now - shouldn't be a big deal as it only happens when doc comments are incorrect

**Comment by wardi** [comment]
Also, please add a data loss warning like the purge command.

**Comment by JackMc** [comment]
So it turns out that when Docopt fails to parse it raises an exception DocoptExit which extends from SystemExit, which we catch and silently exit on

**Comment by JackMc** [comment]
97eeb537b27d84d4b07068f3dd71b6385e093adc Adds the prompt.

**Comment by wardi** [comment]
@JackMc huh. raising a SystemExit subclass for an actual failure seems broken.

**Comment by dborzov** [comment]
docopt parses `datacats --version` by printing out the version and raising SystemExit.
To make sure SystemExit is ignored by the undocumented exception wrapper, I made it being parsed differently: (see here)[https://github.com/datacats/datacats/pull/174/files#diff-e4ca613e9fadf3d7fc2c57b7dc2f6a4bR106].

DocoptExit is probably a subclass of SystemExit.

**Comment by JackMc** [comment]
Yup, I dunno how we would handle it, though. It's more of a programming error

**Comment by wardi** [comment]
report it as a docopt bug if that's what's really happening?

**Comment by wardi** [comment]
oh, and add some functional tests to verify that reset actually works...

**Comment by JackMc** [comment]
Done.

**Comment by wardi** [comment]
:red_circle: How about doin' this on a branch next time :smirk:

**Comment by JackMc** [comment]
Yeah >.>

**Comment by dborzov** [comment]
![thatguy](https://cloud.githubusercontent.com/assets/816895/8163791/26b46496-1353-11e5-9e56-6beb66a9c338.jpg)

branches are for sheep, we sharks only push on master

**Comment by JackMc** [comment]
:laughing:

**Comment by JackMc** [comment]
Seems like the venv gets deleted somehow

**Comment by JackMc** [comment]
That should fix it, turns out the purge never_delete option was broken!

**Comment by JackMc** [comment]
Yayyyyyy :green_heart:

**Comment by JackMc** [comment]
Sorry about this guyssss :cry:

**Comment by JackMc** [comment]
Is this good to close?

**Comment by wardi** [comment]
Noticed one more thing: this looks like the site should be running after a reset, but I have to run start again myself.  `reset` needs an `--image-only` like create and init

```
(venv)ian@moby3:~/environments/bare/ckan$ datacats reset
Reset will remove all data related to the site primary and recreate the database. Are you sure? [n] (y/n): y
Resetting...
Creating environment bare/primary from existing environment directory "bare".....
Initializing database
Starting web server at http://127.0.0.1:5565/ ...
admin user password:
confirm password:
(venv)ian@moby3:~/environments/bare/ckan$ datacats open
Site not currently running
```

**Comment by JackMc** [comment]
How does the ckanapi tool get installed in the virtualenv?

**Comment by wardi** [comment]
@JackMc I think we sneak that in from the docker image. When we install --clean it goes away, which isn't a good thing.

**Comment by JackMc** [comment]
This is sorted in #231
