### ISSUE TITLE
lessc call might not wait

### ISSUE THREAD

**Issue by wardi** [datacats/datacats#196]
The compile_less call immediately tries to remove the container without calling wait the way that docker.web_command does.

https://github.com/datacats/datacats/blob/master/datacats/environment.py#L1092-L1097

Why not use web_command instead? (pass in the node image this function isn't specific to commands run on the web container despite its name) 

Also a docstring wouldn't hurt :-)

**Comment by JackMc** [comment]
I thought that since detach=False this wouldn't be an issue

**Comment by wardi** [comment]
Ok, that makes sense. I'd like to reduce the number of different ways we're calling in to docker-py. We can talk tomorrow.
