### ISSUE TITLE
datacats install "no such file" errors inside docker container

### ISSUE THREAD

**Issue by florianm** [datacats/datacats#201]
I'm trying to setup a few extensions with requirements outside pip install _packagename_:

* [My fork](https://github.com/florianm/ckanext-scheming) of ckanext-scheming [requires Leaflet-draw](https://github.com/open-data/ckanext-scheming/compare/master...florianm:master#diff-b4ef698db8ca845e5845c4618278f29aR4), which runs `pip install -e git+https://github.com/Leaflet/Leaflet.draw.git#egg=leaflet-draw`
* [ckan-galleries](https://github.com/DataShades/ckan-galleries/issues/1) requires mysql_config, which can be fixed in a non-docker install with `sudo apt-get install libmariadbclient-dev`

Both throw a "no such file" error, e.g. the leaflet-draw error:

```
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/var/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.0.0dev1-py2.7.egg/datacats/cli/main.py", line 96, in main
    return command_fn(environment, opts)
  File "/var/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.0.0dev1-py2.7.egg/datacats/cli/install.py", line 34, in install
    install_all(environment, opts['--clean'], verbose=not opts['--quiet'])
  File "/var/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.0.0dev1-py2.7.egg/datacats/cli/install.py", line 85, in install_all
    environment.install_package_requirements(s, sys.stdout if verbose else None)
  File "/var/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.0.0dev1-py2.7.egg/datacats/environment.py", line 965, in install_package_requirements
    stream_output=stream_output
  File "/var/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.0.0dev1-py2.7.egg/datacats/environment.py", line 998, in user_run_script
    stream_output=stream_output
  File "/var/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.0.0dev1-py2.7.egg/datacats/environment.py", line 1031, in run_command
    commit=True, stream_output=stream_output)
  File "/var/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.0.0dev1-py2.7.egg/datacats/docker.py", line 200, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /scripts/run_as_user.sh /scripts/run.sh /project/ckanext-scheming/requirements.txt
    Docker Error Log:
    Requirement already satisfied (use --upgrade to upgrade): ckanapi in /usr/lib/ckan/lib/python2.7/site-packages (from -r /project/ckanext-scheming/requirements.txt (line 1))
Obtaining leaflet-draw from git+https://github.com/Leaflet/Leaflet.draw.git#egg=leaflet-draw (from -r /project/ckanext-scheming/requirements.txt (line 4))
  Cloning https://github.com/Leaflet/Leaflet.draw.git to /usr/lib/ckan/src/leaflet-draw
  Running setup.py (path:/usr/lib/ckan/src/leaflet-draw/setup.py) egg_info for package leaflet-draw
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
    IOError: [Errno 2] No such file or directory: '/usr/lib/ckan/src/leaflet-draw/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  File "<string>", line 17, in <module>
IOError: [Errno 2] No such file or directory: '/usr/lib/ckan/src/leaflet-draw/setup.py'
```

`datacats shell` gets me into the data folder. We need to go deeper.
How would I go about apt-get installing system packages, and pip installing git repos as eggs into the docker container during the `datacats install` step?

**Comment by JackMc** [comment]
I'll look into this now. We should definitely have a way to install packages in the web container.

**Comment by florianm** [comment]
Would running the necessary install steps inside a container and saving it as a new image work? That would be cool so every datacats user could create his/her own set of images (and bugs). 

Or, if it were possible to identify the few missing steps (like my Leaflet-draw egg or the sql client aptitude package) which could be added to the ckan image's dockerfile once, then be distributed by default?

**Comment by wardi** [comment]
any python packages you add in the environment source directory, and any dependencies in requirements.txt get installed by `datacats install`

apt-get install would have to be done in the datacats/web container. You *can* use docker to run commands then commit the image as datacats/web. That will break deploying to datacats.com and will get overwritten the next time you `datacats pull`, but should work fine otherwise.

**Comment by wardi** [comment]
@florianm Our plan is to add packages that users find useful to the web image used by datacats so that deploying and sharing sites is easy. Just let us know what you need added, or better yet submit a PR that adds what you need to https://github.com/datacats/datacats/blob/master/docker/web/Dockerfile .

**Comment by florianm** [comment]
Thanks @wardi, I'll do that. Top of my wish list are the two issues mentioned above, then also a message queue (separate image?), redis or rabbitmq for the harvester, archiver, and qa extensions.

**Comment by JackMc** [comment]
We could definitely do a redis container, there is already a pre-baked one on Docker Hub

**Comment by wardi** [comment]
@florianm yes, we're planning to add redis support for #52

**Comment by JackMc** [comment]
Redis support is added in #234
