### ISSUE TITLE
Enable local development and contributions to upstream

### ISSUE THREAD

**Issue by florianm** [datacats/datacats#210]
If datacats would like to get contributions to base images back from users, could the docs get some info on:

* how to modify docker images locally
* how to use locally modified docker images in place of official datacat ones
* how to contribute successful modifications upstream

Currently, the used docker images are hard-coded. Would it be feasible to have a config, which defaults to currently used / confirmed working images, but can be set by users to use locally modified images?

Example user stories:

* I want to install ckan-galleries, which requires a few modifications to the "web" image. There are requirement conflicts with CKAN master (requests package), which probably can't be accommodated at the same time, so I'll have to keep two "web" images side by side. I still want to be able to run a vanilla CKAN. If any workable solution can be found, I would like to PR my modifications upstream.

* I want to develop on a fork of existing extensions (spatial and scheming), which also requires a few unusual additions to the "web" image. These additions will not be appropriate to be part of the official datacats "web" image until my modifications have made their way into the upstream master. Therefore, I want to be able to keep a few extra images around locally which I don't plan on submitting upstream.

**Comment by deniszgonjanin** [comment]
Great suggestions. We'll update the docs.

In the meantime, to update a local image:
```
$ docker run -datacats/web apt-get install -y whatever
$ docker ps -lq
6f51fba7febb
$ docker commit 6f51fba7febb datacats/web
```
This image will be used until you do a `datacats pull` the next time. You can do run/commit as many times as you'd like, but if you're making a lot of changes you'll want to change the actual Dockerfiles in the source and rebuild them:
```
cd datacats/docker
docker build -t datacats/web . 
```

There is no built-in way to use multiple images. It's baked in at multiple places. 

ckanext-spatial support just landed in master yesterday, if postgis is what you need.

**Comment by florianm** [comment]
Thanks for the quick help, Denis! I went `docker exec -it "ID" bash`, but got a conflict after committing my changes.
cd mod

**Comment by florianm** [comment]
Solution addresses my question, sent PR to docs.
