### ISSUE TITLE
Issue with datapusher on reload

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#215]
I run into this issue on `datacats reload`. However, if I shut down my boot2docker VM and restart it, I am able to do `datacats start` successfully, but **only once**. If I do `datacats reload` or `datacats stop` then `datacats start`, the same error is thrown:

```
(datacats)dzs-MacBook-Pro:ottawa dz$ datacats reload
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats reload

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/Users/dz/source/datacats/datacats/cli/main.py", line 99, in main
    return command_fn(environment, opts)
  File "/Users/dz/source/datacats/datacats/cli/manage.py", line 98, in reload_
    log_syslog=opts['--syslog'])
  File "/Users/dz/source/datacats/datacats/environment.py", line 731, in start_ckan
    datapusher=datapusher)
  File "/Users/dz/source/datacats/datacats/environment.py", line 820, in _run_web_container
    log_syslog=log_syslog
  File "/Users/dz/source/datacats/datacats/docker.py", line 286, in run_container
    port_bindings=port_bindings)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/docker_py-1.2.2-py2.7.egg/docker/utils/decorators.py", line 15, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/docker_py-1.2.2-py2.7.egg/docker/client.py", line 1063, in start
    self._raise_for_status(res)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/docker_py-1.2.2-py2.7.egg/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("Cannot start container 9064b531c08714ed3f939a7edf64125ff86f28cd71051cc514697420c48ffb2d: Cannot link to a non running container: /datacats_datapusher_ottawa_primary AS /datacats_web_ottawa_primary/datapusher")

```

**Comment by JackMc** [comment]
Does this happen on every reload of any arbitrary environment?

**Comment by deniszgonjanin** [comment]
No, I'm testing on a newer environment and it does not happen. It's happening to me right now only on one specific environment, which is a bit older.

I could do a purge and init, and that would likely fix it. But then we won't know what the problem might have been

**Comment by JackMc** [comment]
Okay, definitely keep the datadir around

**Comment by JackMc** [comment]
This is probably related to the way we handle the lack of data pusher in an environment

Can you try reproducing it with ``datacats create --no-datapusher``? I'm gonna try it on my machine too but would like to see if it's something to do with your env

**Comment by JackMc** [comment]
I cannot reproduce it with that option

**Comment by deniszgonjanin** [comment]
No, me neither. I will do a purge but I don't think it has anything to do with the data itself. I'll poke around some more

**Comment by deniszgonjanin** [comment]
This is caused by old environments not having the datapusher source in the project directory

**Comment by JackMc** [comment]
Ok, will investigate.

**Comment by JackMc** [comment]
How old are we talking? Was the environment converted to multisite or was it post-mulitiste?

**Comment by JackMc** [comment]
I cannot reproduce with a simple rm -rf of the datapusher dir and removing it from the ckan.plugins

**Comment by deniszgonjanin** [comment]
It's OK to just close it I think, there's a paper trail here in case anyone
runs into it

Denis (from mobile)
