### ISSUE TITLE
datacats less and datacats-lesscd should spit out compilation errors

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#220]
Right now compiling less fails silently if there is a less syntax error. This leaves it up to the designer to figure out where the syntax errors are.

It should instead spit out errors. The errors are reported if the less container is ran manually, so that output could be spat out instead

**Comment by JackMc** [comment]
Will do this now

**Comment by deniszgonjanin** [comment]
Fixed by #221
