### ISSUE TITLE
datacats logs -d is broken

### ISSUE THREAD

**Issue by dborzov** [datacats/datacats#228]
"datacats logs -d" expects an env_name parameter though docopts and then ignores it

**Comment by JackMc** [comment]
https://github.com/datacats/datacats/blob/master/datacats/cli/manage.py#L177-L195 it doesn't seem that -d exists anymore

**Comment by JackMc** [comment]
Which is weird that it's even accepting a -d

**Comment by JackMc** [comment]
Can you link to the container lookup?

**Comment by dborzov** [comment]
I am addressing this

**Comment by dborzov** [comment]
@JackMc oh you are right, `datacats logs` work ok,  `-d` issue aside. I did not check out to the most recent version, my bad :--/

**Comment by dborzov** [comment]
everything works as it should on my machine :+1:
