### ISSUE TITLE
document clear manual steps for cleaning a directory

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#241]
Related to #240 

If `datacats migrate` fails, no datacats commands can be used on the environment. This includes `purge`. To the user, it is not clear how to recover from `migrate` failing.

Ideally `purge` should always work regardless of the format version. If that is too difficult, we should print out a message with some instructions for cleaning the environment manually when `datacats purge` fails.

**Comment by JackMc** [comment]
:+1:

**Comment by JackMc** [comment]
I think it's a better idea for us to just fallback to removing containers for the old format. More user-friendly.

**Comment by JackMc** [comment]
#268 takes a stab at fixing things
