### ISSUE TITLE
Package dependencies for extensions

### ISSUE THREAD

**Issue by makkus** [datacats/datacats#246]
Quick question, sorry if there is an obvious solution for this: I'm trying to use the ckanext-ldap extension, which has python-ldap as a pip requirements, which in turns needs some debian package installed (libsasl2-dev if I recall right, probably something else too). 

Is there a generic way to install dependencies like that with datacats? I.e. something like a requirements.txt file, just for debian packages?

**Comment by JackMc** [comment]
The current solution for this is to change the dockerfile in docker/web/Dockerfile and submit a pull request.

**Comment by JackMc** [comment]
A quick hack to make this work until your PR is accepted:

* ``docker exec -it datacats_web_yourenv_primary apt-get install libsasl2-dev`` This will make your single environment have the package(s) installed.
* ``docker commit -t datacats/web datacats_web_yourenv_primary`` This will make this the template from which any future environments are made until your next ``datacats pull``

**Comment by makkus** [comment]
Ok, sweet, will do. Thanks.
