### ISSUE TITLE
`datacats pull` should fetch redis

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#270]
When the user does `datacats tweak --add-redis`, they first need to do `docker pull redis`, which is not explained anywhere in the docs and people unfamiliar with docker will not know what to do.

Since redis is needed for qa, harvester, and some other things, either the image should be pulled as part of `pull` or as part of `tweak --add-redis`

**Comment by JackMc** [comment]
``tweak --add-redis`` should pull down the redis container next time you load the environment

**Comment by JackMc** [comment]
Alternatively you can do ``datacats pull --all`` and it will pull it down for you with all the other images
