### ISSUE TITLE
datacats reset & datacats install should strip .pyc files from environment

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#281]
For myself, a common use case for `datacats reset` is when I am switching between CKAN versions and I need a clean database.

If there are old .pyc files around, the database [migrations fail](http://docs.ckan.org/en/ckan-1.6/common-error-messages.html#assertionerror-there-is-no-script-for-46-version) when downgrading from a newer CKAN version to the old one.

I don't think there is any downside to cleaning out these files. Can they be removed automatically?

**Comment by JackMc** [comment]
Hmm, they probably could. Would it be useful if we did it for all installed extensions also?

**Comment by deniszgonjanin** [comment]
The extensions haven't caused me trouble, but if we're doing ckan/ let's do everything else as well
