### ISSUE TITLE
Data migration instructions from non-datacats CKAN to a datacats CKAN

### ISSUE THREAD

**Issue by florianm** [datacats/datacats#291]
Is there a clean migration path from an existing CKAN to datacats?
I'm assuming that the data schema is the same (e.g. using the same custom ckanext-scheming dataset schema on both ends, or the default).

Maybe there's a better way, but I've done so far:

* `paster db dump` the existing (source install master, about two months old) CKAN db to an sql file (as root with ckan virtualenv activated)
* copy and chown the file to my current user (as which I'm running datacats) and to my current datacats environment
* upgraded datacats web container to fix #290 
```
docker run datacats/web:latest apt-get install -y postgresql-client-9.3
docker ps -lq
(returns hash of changed image)
docker commit (hash) datacats/web:latest
```
* `datacats reload`
* cd into datacats environment and `datacats shell`
* in the datacats shell: `(ckan)shell@internal:~$ paster --plugin=ckan db load my_backup.sql`
* copy and chown storage/resources to data dir (I need to double-check that files are at the correct folder  level)

Currently I'm stuck after enabling ckanext-spatial with "no postgis installed" in the datacats db after the db load step (loading the export from the postgis/spatial enabled source CKAN).

Has anyone ever migrated production data from existing CKANs into a datacats CKAN?

**Comment by deniszgonjanin** [comment]
So, we have a bunch of clients and while they don't all use datacats in production (yet), we have datacats environment for each to use in development and staging. Each time, we have had to go through the process of getting a non-datacats CKAN environment migrated to datacats.

Usually I start with a new datacats env, and then install the same list of extensions they have, while matching the ini settings. For data I usually don't need the database dump, and I end up using `ckanapi` to just dump some datasets on the command line and load them into my environment. 

So I guess that's why there are some rough edges here. We don't often dump and load the whole db, which is why there are some unresolved problems here. We should be doing that because it would actually be faster to load the db directly than using the API to do it.

I would say, log individual issues on what doesn't work with the workflow you describe above, because that workflow is best practice and it should be working better.

**Comment by florianm** [comment]
`db_dump` will become tricky with custom data schemas from ckanext-scheming. I like your approach of scripting the export/import through the ckanapi as it looks flexible enough to customise the field mapping, but automatable and reproducible. Also, it's the beginning for a custom harvester should the process need to run repeatedly.

**Comment by florianm** [comment]
@deniszgonjanin how do you migrate users from legacy ckans into datacats ckans? The 
CKAN API does not export the password hashes, right?

**Comment by deniszgonjanin** [comment]
@florianm that's right, it won't export them for any ckan before 2.5, so the only way to export users w/ hashes from any CKAN is to do a db dump.

**Comment by florianm** [comment]
Current procedure works for CKAN 2.5.0a source install to datacats latest (2.5.0a), except for an issue with postgis not being installed.

* paster db dump source ckan db
* rsync files and db dump to target datacats CKAN
```
(source install CKAN venv)root@machine:/path/to/ckan# paster --plugin=ckan db dump -c /path/to/ckan/config.ini db-DATE.sql
```
Restore db dump as per http://datawagovau.readthedocs.org/en/latest/ckan.html#restore:
```
datacats paster db clean
datacats paster db load /project/db-DATE.sql
datacats reload
```

Data, resource files, users are all there, only once enabling ckanext-spatial in the .ini, we'll get:
```
[...]
    setup_model()
  File "/project/ckanext-spatial/ckanext/spatial/model/package_extent.py", line 30, in setup
    'Please refer to the "Setting up PostGIS" section in the README.')
Exception: The spatial extension is enabled, but PostGIS has not been set up in the database. Please refer to the "Setting up PostGIS" section in the README.
```

So my pinch is:
* The db dump doesn't restore postgis
* after `datacats paster db load`, a `datacats tweak --install postgis` is without effect (see also #353 )
* `datacats paster db clean`, `datacats tweak --install postgis`, `datacats paster db load`, `datacats reload` with ckanext-spatial enabled in config also crashes on missing postgis.
* `datacats paster db clean`, `datacats paster db init`, `datacats tweak --install postgis`, enabling ckanexts-spatial in config, `datacats start` also crashes on missing postgis.

Next I'll try to psql into the datacats db to see whether postgis is installed, and whether I can install it manually.

**Comment by florianm** [comment]
Last try: only pg_dump users from source install CKAN and paster db load them, then import the rest via ckanapi.

```
# dumping the legacy CKAN's user table actually works:
pg_dump -h localhost -p 5432 -d CKAN_DBNAME -U CKAN_DBUSER -t user -a > user.sql    Password: CKAN_DBUSER_PASSWORD

# restoring user.sql doesn't:
(datacats)florianm@aws-eco-001:/mnt/projects/datacats/internal$ datacats paster db load /project/user.sql
/project/ckan/ckan/new_authz.py:6: FutureWarning: ckan.new_authz has been renamed to ckan.authz. The ckan.new_authz module will be removed in a future release.
  FutureWarning)
2015-10-30 08:13:50,712 DEBUG [ckanext.showcase.model] ShowcasePackageAssociation table defined in memory
2015-10-30 08:13:50,714 DEBUG [ckanext.showcase.model] ShowcasePackageAssociation table already exists
2015-10-30 08:13:50,715 DEBUG [ckanext.showcase.model] ShowcaseAdmin table defined in memory
2015-10-30 08:13:50,716 DEBUG [ckanext.showcase.model] ShowcaseAdmin table already exists
Traceback (most recent call last):
  File "/usr/lib/ckan/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/project/ckan/ckan/lib/cli.py", line 238, in command
    self.load()
  File "/project/ckan/ckan/lib/cli.py", line 315, in load
    pg_cmd = self._postgres_load(dump_path)
  File "/project/ckan/ckan/lib/cli.py", line 288, in _postgres_load
    assert not model.repo.are_tables_created(), "Tables already found. You need to 'db clean' before a load."
AssertionError: Tables already found. You need to 'db clean' before a load.
```

Seems `ckan/ckan/lib/cli.py` is too clever for it's own good.
So I definitely need a way to psql into the datacats db, and anyone else who migrates existing users does so too - unless there's a cleverer/working way of migrating CKANs?

**Comment by florianm** [comment]
Figured it out.

# Migrating CKAN from legacy source install to datacats

## Create minimal CKAN environment
```
datacats create --ckan latest --site-url http://new-ckan envname 5000
cd envname
datacats tweak --install-postgis
datacats install
datacats reload --address=0.0.0.0
```
`--address=0.0.0.0` makes CKAN open the port to the outside world, YMMV.

## Migrate only legacy users
```
sudo su
sudo -u postgres pg_dump -a -O -t user -f /path/to/datacats/envname/user.sql ckan_default 
sudo chown ubuntu:ubuntu /path/to/datacats/envname/user.sql
# delete line "default" from user.sql -- datacats already has a default user
```

in datacats env `/path/to/datacats/envname`:
```
cat ~/.datacats/ENV_NAME/sites/primary/passwords.ini
# prints passwords -- copy the postgres password

(datacats venv)me@machine:/path/to/ENV_NAME⟫ datacats shell
datacats shell
(ckan)shell@ENV_NAME:~$ psql -h db -d ckan -U postgres -f user.sql
(paste the postgres user's password)
exit
```

## Install extensions
As required, git clone extensions and `datacats install` and enable in .ini, reload.

## Migrate resource and upload files
```
sudo rsync -Pavvr /path/to/old/ckan/storage/uploads/group/ /mnt/ckan/datacats_data/internal/sites/primary/files/storage/uploads/group/
sudo rsync -Pavvr /path/to/old/ckan/resources/ /mnt/ckan/datacats_data/internal/sites/primary/files/resources/
```

## Migrate groups, orgs, datasets
``
ckanapi dump groups --all -r http://old-ckan | ckanapi load groups -r http://new-ckan -a API_KEY
ckanapi dump organizations --all -r http://old-ckan | ckanapi load organizations -r http://new-ckan -a API_KEY
ckanapi dump datasets --all -r http://old-ckan | ckanapi load datasets -r http://new-ckan -a API_KEY
```
