### ISSUE TITLE
Datacats docker images not pulling

### ISSUE THREAD

**Issue by florianm** [datacats/datacats#294]
Are the datacats images unavailable just now?

I've just pulled `datacats pull -a` (redis not part of it) successfully, created a new ckan latest environment, added redis, now getting stuck in `datacats reload` (which is now trying to pull the redis image).

Also `datacats pull` is stuck too.

docker info says:
```
Containers: 5
Images: 147
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-61-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.859 GiB
Name: ip-172-31-22-195
ID: MARO:UQVK:SLGK:UPJN:4XHM:A2N2:Y3QJ:RQYN:GGAL:WZCF:5CMI:PKQX
WARNING: No swap limit support
```
df -h says I'm not out of HD space either.

Pulling from a separate VM is stuck too.

Edit: https://status.docker.com/ reports full service disruption of docker registry API. Not your fault!
Edit 2: a luxury feature would be to get some kind of hint to check https://status.docker.com/ if `docker pull` times out.

**Comment by JackMc** [comment]
Hi there, 

I'm just about to get into the office, will investigate this ASAP.

**Comment by florianm** [comment]
@JackMc thanks for the quick reply! Seems dockerhub had some troubles with their AWS/S3 which seem to be resolved - datacats pull is running fine again! Hence closing as unrelated to datacats. Phew!
