### ISSUE TITLE
Creating a new site overwrites development.ini

### ISSUE THREAD

**Issue by JackMc** [datacats/datacats#298]
This is a release blocker for multisite

**Comment by JackMc** [comment]
It appears the issue is not as simple as this.

**Comment by deniszgonjanin** [comment]
the plot thickens

**Comment by JackMc** [comment]
![dun-dun-dun-o](https://cloud.githubusercontent.com/assets/746519/9252694/c1572d12-41a7-11e5-927b-ba8db07c53d5.gif)

**Comment by JackMc** [comment]
Turns out I just didn't pass a parameter... My fault! Datacats is bugless :tm:
