### ISSUE TITLE
Webserver started at different ip address after reload

### ISSUE THREAD

**Issue by makkus** [datacats/datacats#299]
So, when I create a datacats instance using the --address flag, the webserver seems to be listening on this interface correctly:

    $ datacats create --address=172.17.42.1 uoa   
    Creating environment "uoa/primary"...........
    Installing ckan
    Installing ckanext-uoatheme
    Installing datapusher
    Installing ckan requirements
    Installing datapusher requirements
    Initializing database
    Starting web server at http://172.17.42.1:5859/ ...
    admin user password:
    confirm password:

But when I do a 'datacats reload', it falls back to listening on 127.0.0.1:

    $ cd uoa                                   
    $ datacats reload
    Starting web server at http://127.0.0.1:5859/ ..

This breaks the datapusher, and also access to the resource. I'm using a linux host and run datacats directly, if that makes any difference.

**Comment by JackMc** [comment]
Hi there,

That does seem to make a difference, I saw this
this afternoon. What version of datacats are you
running?

**Comment by makkus** [comment]
$ datacats --version
1.0.3

**Comment by JackMc** [comment]
Okie dokie, working on this now :)
