### ISSUE TITLE
Test workflow with Docker Toolbox

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#300]
[Docker Toolbox](https://blog.docker.com/2015/08/docker-toolbox/) is the new recommended way to get started with Docker. So, we should make sure datacats installs easily after a toolbox installation, and also update the [docs](http://docs.datacats.com).

**Comment by JackMc** [comment]
This isn't just a docs issue - our checking code is broken

**Comment by byndcivilization** [comment]
Is there any idea when datacats will work with Docker Toolbox?

**Comment by wardi** [comment]
is this fixed by #317 ?

**Comment by byndcivilization** [comment]
I updated datacats from pip and its still giving me this:
Pulling image datacats/webPulling image datacats/web failed. Retrying.Pulling image datacats/webPulling image datacats/web failed. Retrying.Pulling image datacats/webPulling image datacats/web failed. Retrying.Pulling image datacats/webPulling image datacats/web failed. Retrying.Pulling image datacats/web----------------------------------------
datacats: problem was encountered:
Failed to pull image datacats/web.
----------------------------------------

**Comment by wardi** [comment]
@byndcivilization please try with the latest master version from github.

**Comment by byndcivilization** [comment]
Nope, it gives me the same message

**Comment by byndcivilization** [comment]
$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64


$ datacats --version
1.1.0

**Comment by byndcivilization** [comment]
$ VBoxManage -v
5.0.0r101573

**Comment by JackMc** [comment]
Do you have your environment variables set correctly (i.e. DOCKER_HOST) using ``docker-machine env dev``

**Comment by byndcivilization** [comment]
Not totally sure to be honest. I just made the switch after holding out.

export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="<path>"
export DOCKER_MACHINE_NAME="dev"

**Comment by byndcivilization** [comment]
It is pulling other images

**Comment by byndcivilization** [comment]
I sort of remember having to route the boot2docker ip address to the boot2docker hostname in the old setup. Is that whats happening here?

**Comment by byndcivilization** [comment]
It's also acting finicky with other commands:
```$ datacats info```
```----------------------------------------```
```datacats: problem was encountered:```
```You have not created your boot2docker VM. Please run "boot2docker init" to do so.```
```----------------------------------------```

**Comment by byndcivilization** [comment]
Seems to be working now. Made the switch to toolbox today but didn't restart my machine after the switch. Shouldn't have made a difference but restart fixed it.

Sorry for the false alarm.

**Comment by wardi** [comment]
Huzzah! Closing this and #312
