### ISSUE TITLE
boot2docker address setting needs better default

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#309]
```
(datacats)dzs-MacBook-Pro:dcats-envs dz$ datacats create testaddress
Creating environment "testaddress/primary"...........
Installing ckan
Installing ckanext-testaddresstheme
Installing datapusher
Installing ckan requirements
Installing datapusher requirements
Initializing database

----------------------------------------
datacats: problem was encountered:
Cannot specify address on boot2docker.
----------------------------------------
```

`.datacats-environment` doesn't set an address by default anymore. `datacats` itself defaults the address to `127.0.0.1`, but then raises an error for said address.

Setting `address` to the boot2docker ip works well. 

A possibly related problem is that I think previous versions of datacats did write `address = 127.0.0.1` into the `.datacats-environment` file, so those may be broken on OSX when users upgrade.

**Comment by wardi** [comment]
Shouldn't address be ignored always when using boot2docker?

**Comment by JackMc** [comment]
Yeah, but it wasn't being due to the == instead of !=

**Comment by wardi** [comment]
No, I mean if an address is specified in the config it's not the same as a user passing it on the command line. We should ignore any address value set in the .datacats-environment file with boot2docker

**Comment by JackMc** [comment]
We basically do that already, except we error if they specify anything other than 127.0.0.1 in there

**Comment by JackMc** [comment]
The reason for the ignoring 127.0.0.1 is backwards compat

**Comment by JackMc** [comment]
I think this is fixed?
