### ISSUE TITLE
Document .datacats-environment

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#314]
We should have some explanations of the `.datacats-environment` settings in the docs. Right now some of those overlap with the .ini settings, and users may find it confusing when they are troubleshooting problems. They might have questions about:
- what the `ckan_version` means and how it works with regard to the ckan verstion checked out in source.
- similarly for port and `site_url`, how are they different and how they interact with the same values in the .ini

**Comment by wardi** [comment]
all those settings can be given on the command line now. I kind of like this file not being a public interface

**Comment by deniszgonjanin** [comment]
Ok. Closing in favour of #305
