### ISSUE TITLE
Error uploading csv and geojson

### ISSUE THREAD

**Issue by reneenoble** [datacats/datacats#319]
I get the following error when uploading some CSVs and geojson.  But it works just find on some csv/geojson files, it just reaks for some of them.  This can happen if I create the dataset with a  link or an upload.

⇝ UndefinedError: 'list object' has no attribute 'iteritems'
URL: http://127.0.0.1:5831/dataset/tax-csv-geo-au/resource_data/8ddb0950-afd0-4bc5-ba2a-f0fcbf2fc01a
File '/usr/lib/ckan/local/lib/python2.7/site-packages/weberror/evalexception.py', line 431 in respond
  app_iter = self.application(environ, detect_start_response)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/fanstatic/publisher.py', line 234 in __call__
  return request.get_response(self.app)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
  response = request.get_response(self.app)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/beaker/middleware.py', line 73 in __call__
  return self.app(environ, start_response)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/beaker/middleware.py', line 155 in __call__
  return self.wrap_app(environ, session_start_response)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/routes/middleware.py', line 131 in __call__
  response = self.app(environ, start_response)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in __call__
  response = self.dispatch(controller, environ, start_response)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch
  return controller(environ, start_response)
File '/project/ckan/ckan/lib/base.py', line 338 in __call__
  res = WSGIController.__call__(self, environ, start_response)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 221 in __call__
  response = self._dispatch_call()
File '/usr/lib/ckan/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 172 in _dispatch_call
  response = self._inspect_call(func)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call
  result = self._perform_call(func, args)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call
  return func(**args)
File '/project/ckan/ckanext/datapusher/plugin.py', line 70 in resource_data
  extra_vars={'status': datapusher_status})
File '/project/ckan/ckan/lib/base.py', line 217 in render
  loader_class=loader_class)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
  return render_func()
File '/project/ckan/ckan/lib/base.py', line 155 in render_template
  return render_jinja2(template_name, globs)
File '/project/ckan/ckan/lib/base.py', line 104 in render_jinja2
  return template.render(**extra_vars)
File '/usr/lib/ckan/local/lib/python2.7/site-packages/jinja2/environment.py', line 894 in render
  return self.environment.handle_exception(exc_info, True)
File '/project/ckan/ckan/templates/package/resource_data.html', line 1 in top-level template code
  {% extends "package/resource_edit_base.html" %}
File '/project/ckan/ckan/templates/package/resource_edit_base.html', line 4 in top-level template code
  {% set res = c.resource %}
File '/project/ckan/ckan/templates/package/base.html', line 3 in top-level template code
  {% set pkg = c.pkg_dict or pkg_dict %}
File '/project/ckan/ckan/templates/page.html', line 1 in top-level template code
  {% extends "base.html" %}
File '/project/ckan/ckan/templates/base.html', line 103 in top-level template code
  {%- block page %}{% endblock -%}
File '/project/ckan/ckan/templates/page.html', line 19 in block "page"
  {%- block content %}
File '/project/ckan/ckan/templates/page.html', line 22 in block "content"
  {% block main_content %}
File '/project/ckan/ckan/templates/page.html', line 57 in block "main_content"
  {% block primary %}
File '/project/ckan/ckan/templates/page.html', line 70 in block "primary"
  {% block primary_content %}
File '/project/ckan/ckan/templates/page.html', line 90 in block "primary_content"
  {% block primary_content_inner %}
File '/project/ckan/ckan/templates/package/resource_data.html', line 28 in block "primary_content_inner"
  {% for error_key, error_value in status.task_info.error.iteritems() %}
UndefinedError: 'list object' has no attribute 'iteritems'

**Comment by deniszgonjanin** [comment]
Hmm. That's definitely a CKAN error. You should post the traceback, as well as (if possible) links to the files that cause this, to the CKAN issue tracker: https://github.com/ckan/ckan/issues

**Comment by wardi** [comment]
I think I've already fixed this issue here: https://github.com/ckan/ckan/pull/2518 give that a try and please +1 on the comments if it fixes your issue.

**Comment by wardi** [comment]
I agree with @deniszgonjanin this looks like a ckan issue, not a datacats one
