### ISSUE TITLE
`--no-initdb` option on `datacats reset`?

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#323]
When loading an existing database into a new datacats instance, it could be useful to skip the db init step, so that a postgres dump can be loaded without having to go through the extra step of doing `paster db clean`, which itself needs a [workaround](https://github.com/ckan/ckan/issues/2306) to work with datacats.

**Comment by JackMc** [comment]
Sounds like a good idea!

**Comment by JackMc** [comment]
Are you working on this or can I?

**Comment by deniszgonjanin** [comment]
it's all yours if you want it

**Comment by JackMc** [comment]
Sounds good :3

**Comment by deniszgonjanin** [comment]
Let's add the same to `datacats init` :smile:

**Comment by JackMc** [comment]
Whoops, I did some code for this and forgot to PR it

**Comment by JackMc** [comment]
Let me grab it

**Comment by JackMc** [comment]
(See #324)
