### ISSUE TITLE
Error uploading csv and geojson

### ISSUE THREAD

**Issue by reneenoble** [datacats/datacats#325]
Hi again, I've still got a problem uploading csv and geojson, I'm getting a different error now that I'm hosting on the datacats server thing.  

This is what I get when I hit upload to datastore on a geojson, this is a geojson that I've grabbed from a working version of ckan somewhere else . So I'm not convinced it's a ckan problem.  This is running on a source install of datacats with the ckan version option = latest.  We speculate it is because of capitalisation.  

```Error: CKAN DataStore bad response. Status code: 409 Conflict. At: http://172.17.15.23:5000/api/3/action/datastore_create. Response: {u'error': {u'__type': u'Validation Error', u'fields': [u'"{ "type": "Feature"" is not a valid field name']}, u'help': u'http://172.17.15.23:5000/api/3/action/help_show?name=datastore_create', u'success': False}```

I also get a similar error for some csv uploads.  Some work find, but if the csv has spaces in the first row then it will give a similar error.  Again this is using csv's link instances where they seem to be uploaded fine.  So again I'm don't understand how it could be a ckan.

**Comment by deniszgonjanin** [comment]
The CKAN datastore doesn't take GeoJSON. The 'Upload to Datastore' button is meant for tabular data only, it doesn't support JSON files. So the error is expected

**Comment by reneenoble** [comment]
ahh thanks for that :) ! What about the CSV? is there strict formatting on csv files, ie. no spaces. It's just a bit strange that CSVs I pull off data.gov.au can't throw an error when I try use them.

**Comment by deniszgonjanin** [comment]
Do you have the error trace for the CSV as well? The one above is for the GeoJSON. 

In general, [datapusher](https://github.com/ckan/datapusher) accepts most well-formed CSV files, but there are a couple of bugs that I know of, where it chokes. You can check their issue tracker as well
