### ISSUE TITLE
Checkout full ckan git repo

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#327]
Many people using datacats conceivably want to develop CKAN itself. Right now this is difficult because datacats checks out a shallow copy of the CKAN git repo. To see what I mean, try to checkout the master branch of ckan from a new datacats environment. 

It took me a while to figure out a proper way to do it, and it seems to be to change `.git/config` from:
```
[remote "origin"]
        url = https://github.com/ckan/ckan
        fetch = +refs/heads/release-v2.4.0:refs/remotes/origin/release-v2.4.0
```
to:
```
[remote "origin"]
        url = https://github.com/ckan/ckan
        fetch = +refs/heads/*:refs/remotes/origin/*
```

... and then do a `git fetch --unshallow`. Only then will you be able to `git checkout master`

It's a hassle to discover this on your own unless you're very good at git. datacats should make it easier to develop for CKAN itself by checking out the whole repo.

**Comment by JackMc** [comment]
I suggest that we **only** do those for the "master" version of the ckan image.

**Comment by JackMc** [comment]
Otherwise we'd be downloading a lot of redundant git history.

**Comment by deniszgonjanin** [comment]
Acceptable and easy alternative is also to have a nicely written section on the docs.datacats.com FAQ on the steps to fetch the history properly.

**Comment by JackMc** [comment]
I like the idea of doing this in the "master has a full checkout" and "docs specify how to get to master from other branches"

**Comment by deniszgonjanin** [comment]
![image](https://cloud.githubusercontent.com/assets/209316/9864333/7ce1409a-5b16-11e5-873c-2974907f80e9.png)

**Comment by JackMc** [comment]
This is now on the docker hub images - do a ``datacats pull`` and make a new env with --ckan=master :-)

**Comment by JackMc** [comment]
I'm gonna write some docs then PR it
