### ISSUE TITLE
--ckan latest contains SQLAlchemy==0.7.8

### ISSUE THREAD

**Issue by florianm** [datacats/datacats#345]
After creating and installing a "latest" environment, pip freeze inside the datacats shell shows SQLAlchemy==0.7.8, which breaks ckanext-spatial with a [well-known bug](http://ckanext-spatial.readthedocs.org/en/latest/install.html#attributeerror-type-object-userdefinedtype-has-no-attribute-comparator). 

This can be fixed with
``` 
datacats shell
pip install SQLAlchemy==0.9.6
exit
datacats reload
```

Why is there SQLAlchemy==0.7.8 in my latest CKAN? There is no mention of that version anywhere in my CKAN or extensions.

**Comment by JackMc** [comment]
Is this datapusher and clan-service-provider again?

**Comment by florianm** [comment]
Actually, the issue has disappeared after:

* `datacats pull -a`,
* `git pull` in the datapusher dir
* `datacats install --clean`

Now the instance suffering from #334 is running fine with datapusher! Closing this one as resolved.
