### ISSUE TITLE
datacats paster db load can't find .sql file

### ISSUE THREAD

**Issue by florianm** [datacats/datacats#353]
Migrating data from a legacy CKAN into a datacats CKAN, I need the user accounts migrated as well (which ckanapi doesn't support). So IIUC I need to dump/load the whole db. While I'm permutating what to dump (schema/users/owners probably not, data definitely yes), I'm running into:

(masked private stuff in all caps)

Step 1: paster db dump the ckan legacy database following [ckan docs](https://ckan.readthedocs.org/en/latest/maintaining/paster.html#dumping-and-loading-databases-to-from-a-file)
```
(CKAN source install venv)root@MACHINE:/path/to/ckan/dbdumps# paster --plugin=ckan db dump -c /path/to/config.ini ckan-DATETIME.sql
```

Step 2: copy to datacats env (for convenience) and chown to unprivileged datacats user

Step 3: datacats paster db clean (success)

Step 4: datacats paster db load - as described in ckan docs, but with datacats prefix, which supplies paster with ini and plugin (ckan):
```
(datacats VENV)ME@MACHINE:/mnt/projects/datacats/ENVNAME$ datacats paster db load ckan-DATETIME.sql
/project/ckan/ckan/new_authz.py:6: FutureWarning: ckan.new_authz has been renamed to ckan.authz. The ckan.new_authz module will be removed in a future release.
  FutureWarning)

ckan-DATETIME.sql: No such file or directory

Traceback (most recent call last):
  File "/usr/lib/ckan/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/project/ckan/ckan/lib/cli.py", line 238, in command
    self.load()
  File "/project/ckan/ckan/lib/cli.py", line 315, in load
    pg_cmd = self._postgres_load(dump_path)
  File "/project/ckan/ckan/lib/cli.py", line 290, in _postgres_load
    self._run_cmd(pg_cmd)
  File "/project/ckan/ckan/lib/cli.py", line 297, in _run_cmd
    raise SystemError('Command exited with errorcode: %i' % retcode)
SystemError: Command exited with errorcode: 1
```

Looking at file permissions, the sql pg_dump of my legacy CKAN has the exact same permissions (rw-r-r) and owner (me) and user group as the .ini file, and it's in the same folder. Is there anything I might have missed?

Related question to #291 , what's the best process to migrate users?
I can rsync storage/resources/uploads and use ckanapi to migrate orgs/groups/datasets, it's only the users and their logins I'm after. @deniszgonjanin you've indicated in #291 that you can script the migration - does that include users, and if so, could I bribe you to tell me how? Happy to PR a section for the docs.

**Comment by deniszgonjanin** [comment]
@florianm try:

```
datacats paster db load /project/ckan-DATETIME.sql
```

The hickup of course is the `/project` prefix for the file, as the directory in the container is mounted at `/project/`, not `/`

This is a very leaky abstraction, but I'm not sure what can be done about it

**Comment by deniszgonjanin** [comment]
@florianm if you need to migrate users, then the best approach is to do the whole database portion of the migration using `paster dump`/`paster load`, as you've done above. Another benefit to that is that it's easier to script, and you can migrate the datastore at the same time using the same approach.

**Comment by florianm** [comment]
Thanks that makes sense, I'll try that!

**Comment by florianm** [comment]
Sure enough, that worked. 

There are remaining issues with postgis as well as db owners mismatching between legacy and datacats dbs. Closing this issue as /project/snapshot.sql works!

**Comment by florianm** [comment]
FWIW, the remaining issues are fixed. To migrate a source install CKAN to a datacats CKAN:

in the source install CKAN's virtualenv:
```
sudo service apache2 stop
paster db dump -c .path/to/config.ini filename.sql
sudo service apache2 start
rsync -Pavvr filename.sql /path/to/datacats/env
rsync -Pavvr /path/to/source/CKAN/files/ DATACATS_DATADIR/ENVNAME/sites/primary/files/
```

in the datacats virtualenv and inside the datacats CKAN env's folder:
```
datacats stop
datacats paster db clean
datacats paster db load /project/filename.sql
datacats start
```

and Bob's your uncle.

**Comment by florianm** [comment]
@deniszgonjanin above example ran into #354 
Working solution documented at https://github.com/datacats/datacats/issues/357#issuecomment-153942166 - HTH
