### ISSUE TITLE
How to psql into the datacats postgres container

### ISSUE THREAD

**Issue by florianm** [datacats/datacats#357]
What's the best way to connect psql to the postgres container? This would help to debug things like #195 #291 #354 or to pick around in the db.
An example would be great in the docs!
Currently, not being able to manually fix postgis on the datacats end breaks my source install to datacats  migration path, as I can't migrate existing users with their passwords.

**Comment by florianm** [comment]
Found it in [install_postgis.sh](https://github.com/datacats/datacats/blob/master/datacats/scripts/install_postgis.sh):

in environment ENV_NAME's folder:
```
cat ~/.datacats/ENV_NAME/sites/primary/passwords.ini | grep ckan_password
ckan_password = THE_DB_PASSWORD
datacats shell
(ckan)shell@ENV_NAME:~$ psql -h db -d ckan -U ckan
Password for user ckan: (paste THE_DB_PASSWORD)
psql (9.3.9)
Type "help" for help.

ckan=> 
```

**Comment by davidread** [comment]
Thanks for writing this up @florianm. However it doesn't work for me as postgresql-client isn't installed - I assume you did this separately? The shell doesn't give me a sudo password to install it.

I found that I could use:

    docker exec -it SHELL_CONTAINER_NAME /bin/bash

To get a root shell into an existing datacats-shell container in which I could install the client and run it. But if there is a better way, I'd be pleased to know.

**Comment by wardi** [comment]
hmm. I can run psql to connect to the database from `datacats shell`, e.g.

```
grep postgres /project/development.ini  # to find the password
psql -h db -d ckan -h db -U ckan
```

**Comment by davidread** [comment]
Thanks Ian, you're dead right. If I create an environment it works like that for me. I have the problem with a datacats environment created by someone else, so something they did must have scuppered it.

**Comment by florianm** [comment]
@davidread on the systems I've tried `psql` I also have postgresql installed system-wide. See also https://github.com/ckan/ckan/issues/3264 for a write-up on accessing the datacats' postgres db.
