### ISSUE TITLE
datacats init issue on macbook air OS X version 10.11.1

### ISSUE THREAD

**Issue by husker** [datacats/datacats#358]
Ran into an issue after executing "./unroll.sh < .extensions" in my cloned bcgov repo. 

datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats init

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/datacats/cli/main.py", line 92, in main
    return command_fn(opts)
  File "/Library/Python/2.7/site-packages/datacats/cli/create.py", line 237, in init
    init_db=init_db)
  File "/Library/Python/2.7/site-packages/datacats/cli/create.py", line 251, in finish_init
    install_all(environment, False, verbose=False, quiet=quiet)
  File "/Library/Python/2.7/site-packages/datacats/cli/install.py", line 66, in install_all
    logs = check_connectivity()
  File "/Library/Python/2.7/site-packages/datacats/docker.py", line 378, in check_connectivity
    detach=False)
  File "/Library/Python/2.7/site-packages/datacats/docker.py", line 279, in run_container
    port_bindings=port_bindings)
  File "/Library/Python/2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/docker/api/container.py", line 343, in start
    self._raise_for_status(res)
  File "/Library/Python/2.7/site-packages/docker/client.py", line 142, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("Cannot start container 597c928c79dd1326b1ae1ed02a4d6e3f986a6fd71421091fa681b12361390b6a: [8] System error: exec: "/project/check_connectivity.sh": permission denied")

**Comment by deniszgonjanin** [comment]
Hi @husker. Can you try first:
```
datacats create
```

to create a fresh clean CKAN environment. If that fails as well in similar fashion, could you try installing datacats (`pip install datacats`) inside a virtualenv and try again?

**Comment by husker** [comment]
sure thing - do you know what arguments  i should pass to datacats create?

datacats create
Usage:
  datacats create [-bin] [--interactive] [-s NAME] [--address=IP] [--syslog]
                  [--ckan=CKAN_VERSION] [--no-datapusher] [--site-url SITE_URL]
                  [--no-init-db] ENVIRONMENT_DIR [PORT]

**Comment by husker** [comment]
@deniszgonjanin ok - so I went the virtualenv route and it's looking better but ended with this message -:

(venv)Jamess-MacBook-Air:venv james$ cd bcgov/
(venv)Jamess-MacBook-Air:bcgov james$ ./unroll.sh < .extensions
Cloning into 'ckanext-bcgov'...
remote: Counting objects: 6862, done.
remote: Total 6862 (delta 0), reused 0 (delta 0), pack-reused 6862
Receiving objects: 100% (6862/6862), 21.25 MiB | 806.00 KiB/s, done.
Resolving deltas: 100% (2708/2708), done.
Checking connectivity... done.
Cloning into 'ckanext-ga-report'...
remote: Counting objects: 2026, done.
remote: Total 2026 (delta 0), reused 0 (delta 0), pack-reused 2026
Receiving objects: 100% (2026/2026), 1020.75 KiB | 913.00 KiB/s, done.
Resolving deltas: 100% (933/933), done.
Checking connectivity... done.
Cloning into 'ckanext-geoview'...
remote: Counting objects: 513, done.
remote: Total 513 (delta 0), reused 0 (delta 0), pack-reused 513
Receiving objects: 100% (513/513), 1.33 MiB | 676.00 KiB/s, done.
Resolving deltas: 100% (196/196), done.
Checking connectivity... done.
Cloning into 'ckanext-googleanalytics'...
remote: Counting objects: 536, done.
remote: Total 536 (delta 0), reused 0 (delta 0), pack-reused 536
Receiving objects: 100% (536/536), 115.14 KiB | 0 bytes/s, done.
Resolving deltas: 100% (231/231), done.
Checking connectivity... done.
Cloning into 'ckanext-hierarchy'...
remote: Counting objects: 161, done.
remote: Total 161 (delta 0), reused 0 (delta 0), pack-reused 161
Receiving objects: 100% (161/161), 84.89 KiB | 0 bytes/s, done.
Resolving deltas: 100% (56/56), done.
Checking connectivity... done.
Cloning into 'ckanext-pdfview'...
remote: Counting objects: 820, done.
remote: Total 820 (delta 0), reused 0 (delta 0), pack-reused 820
Receiving objects: 100% (820/820), 2.98 MiB | 1.04 MiB/s, done.
Resolving deltas: 100% (276/276), done.
Checking connectivity... done.
Cloning into 'ckanext-scheming'...
remote: Counting objects: 1859, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 1859 (delta 0), reused 0 (delta 0), pack-reused 1853
Receiving objects: 100% (1859/1859), 273.82 KiB | 430.00 KiB/s, done.
Resolving deltas: 100% (956/956), done.
Checking connectivity... done.
Cloning into 'ckanext-spatial'...
remote: Counting objects: 3764, done.
remote: Total 3764 (delta 0), reused 0 (delta 0), pack-reused 3764
Receiving objects: 100% (3764/3764), 3.00 MiB | 989.00 KiB/s, done.
Resolving deltas: 100% (1653/1653), done.
Checking connectivity... done.
Cloning into 'ckan'...
remote: Counting objects: 136239, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 136239 (delta 6), reused 0 (delta 0), pack-reused 136214
Receiving objects: 100% (136239/136239), 100.70 MiB | 1.09 MiB/s, done.
Resolving deltas: 100% (98391/98391), done.
Checking connectivity... done.
Note: checking out '3be1092331805b0a85c998ef16eaefc2bfef0086'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Cloning into 'datapusher'...
remote: Counting objects: 1046, done.
remote: Total 1046 (delta 0), reused 0 (delta 0), pack-reused 1046
Receiving objects: 100% (1046/1046), 454.70 KiB | 536.00 KiB/s, done.
Resolving deltas: 100% (571/571), done.
Checking connectivity... done.

----------------------------------------
datacats: problem was encountered:
Site named primary already exists.
----------------------------------------

**Comment by deniszgonjanin** [comment]
just need to cleanup the old environment that got stuck, then re-create:
```
datacats purge
datacats init
```

**Comment by husker** [comment]
thanks @deniszgonjanin  - that did the trick. it's running now.
