### ISSUE TITLE
ubuntu 14.04 error 

### ISSUE THREAD

**Issue by husker** [datacats/datacats#360]
thought i'd give ubuntu a try and i'm running into an error  - not sure what the first publickey  error  is but the 2nd seems to be an issue with wget. i'm not using boot2docker and wget -q --spider -T 5 https://pypi.python.org/simple works from the command line.

-------------------------
(dev)james@james-ubuntu:~/projects/bcdc/dev/bcgov$ ./unroll.sh < .extensions
Cloning into 'ckanext-bcgov'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Creating environment bcgov/primary from existing environment directory "bcgov".../home/james/projects/bcdc/dev/local/lib/python2.7/site-packages/docker/utils/utils.py:486: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
.
----------------------------------------
datacats: problem was encountered:
Couldn't connect to PyPi. Is your DNS configured correctly?

If you're using boot2docker, try restarting the VM:
boot2docker down
boot2docker up

----------------------------------------

**Comment by deniszgonjanin** [comment]
this is most definitely a networking problem with Docker. Make sure docker is configured so that containers can access the external network. You can test whether this is the case by running a container like this:

```
docker run busybox ping google.com
```

If you can ping google, your network should be setup correctly.
