### ISSUE TITLE
Running datacats containers without datacats ci

### ISSUE THREAD

**Issue by byndcivilization** [datacats/datacats#366]
Is there currently a way to run datacats containers without running the full ci tool? There have been too many breaking changes to maintain a stable build with the current set up. It would also really help to create a good disaster recovery strategy for AWS deployments since there is no way currently to maintain dev/prod parity using docker-machine and datacats.

**Comment by wardi** [comment]
Sure. The datacats/ckan docker images are just vanilla ckan, those could be run seperately from the CLI tool or datacats as a library. They can also be forked and maintained separately if you choose by starting from the dockerfiles from the docker directory.
