### ISSUE TITLE
datacats doesn't honour port set in .datacats-environment at start or reload

### ISSUE THREAD

**Issue by florianm** [datacats/datacats#373]
I've got a handful of datacats environments, all with their own custom port and site URL assigned in individual `.datacats-enviornment` files:

```
[datacats]
name = private
ckan_version = latest
extra_containers = redis

[site_primary]
port = 5000
site_url = http://my-ckan.org
address = 0.0.0.0

[deploy]
target = datacats@command.datacats.com
```

I've had the same instances unchanged in production since October 2015. Since an OS update yesterday (Ubuntu 14.04 upgrade) and reboot of the VM, all of a sudden, datacats won't recognise my ports any more. Has anything changed on the datacats end?

**Comment by JackMc** [comment]
That is really, really weird. Things haven't been changing on this end so a recent Docker update may have broken this

**Comment by florianm** [comment]
Solved - my server restart resurrected Apache, which previously hosted my three CKANs (on ports 5000, 5001 and 5002).
Here's how I found it:
```
# make sure all docker containers are stopped
docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

# inject some print debugging statements
/mnt/projects/datacats$ datacats reload private
Environment.start_ckan() got PortAllocationError for port 5000
_next_port returns 5001
Environment.start_ckan() got PortAllocationError for port 5001
_next_port returns 5002
Environment.start_ckan() got PortAllocationError for port 5002
_next_port returns 5003
Starting web server at http://0.0.0.0:5003/ ...

# who is hogging my ports 5000-5002?
sudo netstat -plant | grep 500                                                                                                                               
tcp        0      0 172.31.13.63:52227      10.6.20.98:4505         ESTABLISHED 1500/salt-minion
tcp        0      0 172.31.13.63:59226      10.6.20.98:4506         ESTABLISHED 1500/salt-minion
tcp6       0      0 :::5000                 :::*                    LISTEN      1926/apache2    
tcp6       0      0 :::5001                 :::*                    LISTEN      1926/apache2    
tcp6       0      0 :::5002                 :::*                    LISTEN      1926/apache2    
```
Stopping the apache2 service and removing the old apache CKAN configs then let datacats use the ports as given per `.datacats-environment` preference.

Datacats did a great job moving on to the next available port. A luxury would be to get a warning if a port is set in the .datacats-environment, but raising a PortAllocationError, to check what's hogging these ports.
