### ISSUE TITLE
Failed to pull image datacats/web

### ISSUE THREAD

**Issue by sckott** [datacats/datacats#378]
I'm trying to follow installation guide at http://docs.datacats.com/guide.html  on Ubuntu 14.04 on DigitalOcean. But I'm running in to a problem here http://docs.datacats.com/guide.html#download-the-necessary-docker-containers on the command `datacats pull`, where I get `Failed to pull image datacats/web` - This happens whether I am as root or if I remove root and login as a non-root user.

The same thing happened whether I used DO's docker droplet (which comes with Docker installed), or removing their Docker install and installing via `wget ...`  as per your instructions. 

`sudo datacats pull` gave the same error on the non-root account

And I made sure to `sudo usermod -aG docker USERNAME`

__Steps can be taken to reproduce the issue__

* spin up DO droplet ubuntu 14.04 1 gb size w/ or w/o docker installed
* I then ran `pip install virtualenv`, then `virtualenv myckan`, then `. myckan/bin/activate`
* Then `pip install datacats`
* Then `datacats pull`
* then the error `Failed to pull image datacats/web`

Thanks!

**Comment by Kyle-Falconer** [comment]
Also running into this problem on fresh Ubuntu 12.04 install locally (not on DigitalOcean).

**Comment by wardi** [comment]
Looks like @JackMc fixed this in https://github.com/datacats/datacats/commit/b436b9cceee039e75af4ab71cf09ddb9614ff766 would you try again with the latest datacats master? If if works for you I'll push out a bugfix release to pypi

```
$ datacats pull
Pulling image datacats/web:latest...............................................................................................................................................................................................................................................................................................
```

**Comment by sckott** [comment]
will try within next day

**Comment by Kyle-Falconer** [comment]
Didn't work for me. I got `Failed to pull image datacats/web:latest.`

**Comment by sckott** [comment]
Okay, `datacats pull` works now 😄 

However, ran into an error on the next step. I can open a new issue if you like - but here's what happened:

After `datacats pull` I tried

```
datacats create catstown
```

And got

```
Creating environment "catstown/primary"../root/myckan/local/lib/python2.7/site-packages/docker/utils/utils.py:625: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
...
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create catstown

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/root/myckan/local/lib/python2.7/site-packages/datacats/cli/main.py", line 92, in main
    return command_fn(opts)
  File "/root/myckan/local/lib/python2.7/site-packages/datacats/cli/create.py", line 62, in create
    init_db=not opts['--no-init-db'],
  File "/root/myckan/local/lib/python2.7/site-packages/datacats/cli/create.py", line 104, in create_environment
    fn()
  File "/root/myckan/local/lib/python2.7/site-packages/datacats/environment.py", line 303, in create_ckan_ini
    ro={scripts.get_script_path('run_as_user.sh'): '/scripts/run_as_user.sh'},
  File "/root/myckan/local/lib/python2.7/site-packages/datacats/environment.py", line 853, in run_command
    commit=True, stream_output=stream_output)
  File "/root/myckan/local/lib/python2.7/site-packages/datacats/docker.py", line 189, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /scripts/run_as_user.sh /usr/lib/ckan/bin/paster make-config ckan /project/development.ini
    Docker Error Log:
    useradd: UID 0 is not unique
```

**Comment by wardi** [comment]
@sckott https://github.com/datacats/datacats/issues/279

**Comment by sckott** [comment]
okay
