### ISSUE TITLE
datacats.com offline

### ISSUE THREAD

**Issue by dersteppenwolf** [datacats/datacats#381]
Probably this is not the right place to ask but at this moment datacats.com is down.
Does it means that  the company behind datacats is shutting down?

**Comment by wardi** [comment]
@dersteppenwolf the company behind datacats is no longer in operation.

The datacats (and ckan-multisite) Open Source code is all still here though, and I use it every day for my CKAN development. I'm afraid I haven't had time to investigate the open issues. I'm hoping to soon though.
