### ISSUE TITLE
deploy to any CKAN hosting provider

### ISSUE THREAD

**Issue by wardi** [datacats/datacats#46]
There is the beginning of this feature in a "deploy" configuration setting in .datacats-environment . The completed feature should allow a complete config section like

```ini
[deploy]
target = my.host.example.com
user = myself
ssh_host_key = my.host.example.com ssh-rsa AAAAB3NzaC....
```

Then `datacats deploy` will rsync to the specified target instead of datacats.com. The ssh_host_key is used to verify that it's talking to the correct server (found in /etc/ssh/ssh_host_key_rsa.pub, or by running ssh-keyscan)

**Comment by deniszgonjanin** [comment]
Related to #98

**Comment by wardi** [comment]
closing in favour of #98
