### ISSUE TITLE
Add support for starting and linking to a redis container, for ckanext-harvest

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#52]
It's fairly easy to do manually, but it's a nice to have for datacats to automatically run a redis container that the harvester can use for it's queue

**Comment by JackMc** [comment]
Should this be another download-when-needed container?

**Comment by wardi** [comment]
yes, I think so.

**Comment by florianm** [comment]
+1 on redis container and any solution for `paster celeryd`!
