### ISSUE TITLE
Generated API endpoints on deployed instances showing up as 'http://localhost:<port>'

### ISSUE THREAD

**Issue by byndcivilization** [datacats/datacats#78]
When I deploy to datacats server, the api endpoints generated by the 'Data API' button for instance show up as 'http://localhost:<port>/...' instead of 'http://<env>.datacats.io/...' The correct endpoints still work so the api is functioning correctly. Also the link in the 'You can also access this registry using the API (see API Docs).' template element also generates correctly.

**Comment by deniszgonjanin** [comment]
Oh, it looks like a CKAN templating problem. Thanks, that's very helpful

**Comment by byndcivilization** [comment]
Maybe, I’m looking at the [api_info](http://nrgidata.datacats.io/api/util/snippet/api_info.html?resource_id=8f6ae8da-8300-4874-b65b-97f34d27dd8b&datastore_root_url=http%3A%2F%2Flocalhost%3A5027%2Fapi%2Faction) endpoint and that’s tell me that it may be an issue with the load function. I'm using the node [dpm](https://github.com/okfn/datapackage-ckan ) load tool thats giving me a separate set of issues. 

The development server on my local machine gives me the same issue with the api_info endpoint but it remaps it when it generates the popup.

**Comment by deniszgonjanin** [comment]
Closing, issue was with dpm

**Comment by byndcivilization** [comment]
Sorry to reopen this but it turns out it wasn't dpm or a theming issue. See status show api call:
http://resourcedata.datacats.io/api/action/status_show
```
{"help": "http://resourcedata.datacats.io/api/3/action/help_show?name=status_show", "success": true, "result": {"ckan_version": "2.3", "site_url": "http://localhost:5024/", "site_description": "", "site_title": "resourcedata", "error_emails_to": null, "locale_default": "en", "extensions": ["datastore", "resource_proxy", "viewhelpers", "pages", "text_view", "recline_view", "recline_map_view", "recline_grid_view", "recline_graph_view", "webpage_view", "resourcedata_theme", "pdf_view", "navigablemap", "choroplethmap", "apihelper", "issues", "officedocs_view", "contact", "hierarchy_display", "hierarchy_form"]}}
```
The weird thing is that this doesn't show up when running local:
```
{"help": "http://boot2docker:5462/api/3/action/help_show?name=status_show", "success": true, "result": {"ckan_version": "2.3", "site_url": "http://boot2docker:5462/", "site_description": "", "site_title": "resourcedata", "error_emails_to": null, "locale_default": "en", "extensions": ["datastore", "resource_proxy", "viewhelpers", "pages", "text_view", "recline_view", "recline_map_view", "recline_grid_view", "recline_graph_view", "webpage_view", "resourcedata_theme", "pdf_view", "navigablemap", "choroplethmap", "apihelper", "issues", "officedocs_view", "contact", "hierarchy_display", "hierarchy_form"]}}
```

**Comment by wardi** [comment]
Ok, I know what this is. We're not setting the correct site_url on the server side.

**Comment by byndcivilization** [comment]
Yeah I tried to edit the deployment.ini template but I guessed you guys are generating that on deployment. Sort of a related question as this will come up when we move to an organization account and want a custom dns. What is the method for custom dns deployment. Is part of the deployment model us supplying the host and you editing the config specs?

**Comment by wardi** [comment]
We do need to regenerate parts of the ini file, including the site_url. We're adding a form to the dashboard to let organization accounts set their custom domains, but for the moment we need to make that change manually.

**Comment by wardi** [comment]
I've just deployed a fix for your site. Let me know if it looks ok now.

**Comment by byndcivilization** [comment]
Works great. Thanks!
