### ISSUE TITLE
Upgrade pip

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#92]
I got this error on a system doing a `datacats install`:
```
Downloading/unpacking markdown (from -r /project/ckanext-ottawa/requirements.txt (line 1))
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement markdown (from -r /project/ckanext-ottawa/requirements.txt (line 1))
Cleaning up...
No distributions at all found for markdown (from -r /project/ckanext-ottawa/requirements.txt (line 1))
Storing debug log for failure in /project/.pip/pip.log
```
Apparently it's related to this: http://stackoverflow.com/questions/21294997/pip-connection-failure-cannot-fetch-index-base-url-http-pypi-python-org-simpl

Solution is to upgrade pip, the particular version of pip in the datacats web image, 1.5.4, seems to be the problem.

**Comment by JackMc** [comment]
Does this happen during any datacats install?

**Comment by deniszgonjanin** [comment]
It's actually happening to me during `datacats init`, but during the install step. I'm looking into it more, I'll let you know exactly what's up

**Comment by JackMc** [comment]
Thank you :)

**Comment by deniszgonjanin** [comment]
Found the root cause - it's something else entirely, opening a different issue and closing this one
