### ISSUE TITLE
Check for DNS resolution inside of containers

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#94]
Running datacats inside an intranet or any server that has custom DNS servers configured may cause errors such as #92 

Issues can be resolved by adding Google's DNS to the list of nameservers.

Either datacats should run containers with the `--dns` docker flag set, or it should at least alert the user when the containers cannot resolve external domains properly.

https://docs.docker.com/articles/networking/#dns

**Comment by JackMc** [comment]
I don't know how enterprise users would feel about us bypassing their DNS and setting our own, so perhaps an alert may be better.

**Comment by deniszgonjanin** [comment]
Well, it's a docker option - docker does it's own DNS, so we're not really messing with their DNS. I think it's fine if the `--dns` option just gets set, even by default

**Comment by JackMc** [comment]
Okay :) Do you think we should have an option in DataCats to specify a DNS, defaulting to 8.8.8.8/8.8.8.4?

**Comment by JackMc** [comment]
Maybe a good solution between the two is to check for a working DNS and if it doesn't exist warn the user and suggest they use a --dns option on Datacats?

**Comment by deniszgonjanin** [comment]
There should definitely be a check that lets the user know what's going on. Otherwise it's hard for them to find out exactly what is going wrong, as DNS resolution is a silent error.

It is tedious to make them specify `--dns` every time though. Perhaps we should make this, as well as #87 , a global setting they could set in their environment files. What does @wardi think?

**Comment by wardi** [comment]
#87 is saving the address setting in the .datacats-environment file, just like the port is saved now.

But, I think those are being saved in the wrong place. .datacats-environment is likely to be shared across systems when someone shares their environment directory. Binding addresses, assigned port numbers and DNS settings (probably environment names too) are all things that should stay with the system they're configured on. That might mean moving them into datadir settings somewhere. We'll have to add a migration for that kind of change.

**Comment by wardi** [comment]
Oh, and even a datadir is the wrong place for a DNS setting. That should be a user global setting, maybe ~/.datacats/system-config or similar

**Comment by JackMc** [comment]
The ConfigParser.read() method takes a list argument, so we can specify a priority of config files (so if a port is specified in .datacats-environment, then it's considered to "override" the one in a global datacats config. Maybe this would be valuable?

**Comment by wardi** [comment]
I can't think of a case that I would want my DNS settings travelling with a datacats environment. It's a system-wide thing and only a system-wide thing.

We might want to have a system-wide default for the bind address that could be overridden in the datadir settings. I'll make an issue for rationalizing our configuration options.

**Comment by JackMc** [comment]
So as I understand it a desirable behaviour would be to run a DNS check at web container create. Warn user if we can't reach PyPi and tell them to specify ``--dns`` on the command line which will set a global dns option for future use

**Comment by JackMc** [comment]
In the instances where this happens would we need to spin up a container to test the user's DNS or can we just do it locally by doing a HEAD request to PyPi?

**Comment by deniszgonjanin** [comment]
Local DNS works fine, it's just the container DNS that is broken

**Comment by JackMc** [comment]
@deniszgonjanin can you check that #140 resolves the issue and gives you an ok error message?

**Comment by wardi** [comment]
I like #140 as a fix for this issue. @deniszgonjanin please reopen if this misses something
