### ISSUE TITLE
Support docker-machine

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#98]
https://docs.docker.com/machine/

As a datacats user, I want to be able to easily deploy my CKAN instance to the cloud of my choice. 

datacats should be able to support docker-machine targets. E.g. I can enter my AWS or DigitalOcean credentials and my local datacats environment will be deployed to the remote docker host.

**Comment by JackMc** [comment]
Can we use this through Python somehow?

**Comment by deniszgonjanin** [comment]
Yes, docker-machine just sets up a remote docker host. Then you point your docker client to that host and everything else works as usual.

**Comment by deniszgonjanin** [comment]
A thing that the remote instance will need is to expose the running container externally. 

If there is one instance only, this can be done via #88

For other cases, it would be useful to have a nginx container to serve as a reverse proxy. One cool way to do it: http://jasonwilder.com/blog/2014/03/25/automated-nginx-reverse-proxy-for-docker/
