### ISSUE TITLE
Image build script doesn't work on Mac OS X

### ISSUE THREAD

**Issue by JackMc** [datacats/datacats#99]
This is because Mac OS X uses the FreeBSD ``readlink`` command, which functions differently.

We use this at https://github.com/datacats/datacats/blob/master/docker/build_images.sh#L11 like this:
```bash
HERE="$(dirname $(readlink -f $0))"
```

The proposed solution from Drupal who seem to have faced the same problem (https://github.com/mglaman/drupal-puphpet/commit/ba3c917c2246aa98fc878e9cbcca5093d53c0eda) as we do is to replace this line with:

```bash
HERE="$(cd "$(dirname "$(dirname "$0")")" && pwd)"
```

As I understand it, this follows one level of symlinks as opposed to ``readlink -f`` which follows unlimited symlinks. Thoughts?

**Comment by deniszgonjanin** [comment]
Yes, this is a long-standing problem. Building the images should work on any Unix platform. Do submit a PR

**Comment by wardi** [comment]
I don't think there's a reason we need to have all symlinks unrolled, let's just do that and fix it later if it is a real problem
